package dev.lost.engine;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.lost.engine.assetsgenerators.BlockStateGenerator;
import dev.lost.engine.assetsgenerators.LangFileGenerator;
import dev.lost.engine.customblocks.customblocks.CustomBlock;
import dev.lost.engine.utils.FileUtils;
import dev.lost.furnace.files.model.Model;
import dev.lost.furnace.files.texture.Texture;
import dev.lost.furnace.files.unknown.UnknownFile;
import dev.lost.furnace.resourcepack.BedrockResourcePack;
import dev.lost.furnace.resourcepack.JavaResourcePack;
import dev.lost.furnace.resourcepack.ResourcePack;
import dev.lost.furnace.utils.PngOptimizer;
import net.kyori.adventure.key.Key;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;
import org.bukkit.configuration.ConfigurationSection;
import org.intellij.lang.annotations.Pattern;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.stream.Stream;

@SuppressWarnings("PatternValidation") // Stupid thing I don't even know why it's here
public class ResourcePackBuilder {

    // TODO: Clean up this class
    public static void buildResourcePack(@NotNull LostEngine plugin, File resourcePackFile) throws IOException {
        JavaResourcePack resourcePack = ResourcePack.java();
        BedrockResourcePack bedrockResourcePack = plugin.getConfig().getBoolean("geyser_compatibility", false)
                ? ResourcePack.bedrock() :
                null;

        resourcePack.mcmeta(64, "LostEngine Resource Pack");
        if (bedrockResourcePack != null)
            bedrockResourcePack.manifest("LostEngine Resource Pack", "Resource pack generated by LostEngine for Geyser compatibility.");

        LangFileGenerator langFileGenerator = new LangFileGenerator();
        File resourceFolder = new File(plugin.getDataFolder(), "resources");
        List<FileUtils.ItemConfig> configs = FileUtils.yamlFiles(resourceFolder);
        BlockStateGenerator blockStateGenerator = new BlockStateGenerator();
        configs.forEach(config -> {
            ConfigurationSection itemsSection = config.config().getConfigurationSection("items");
            if (itemsSection != null) {
                for (String key : itemsSection.getKeys(false)) {
                    ConfigurationSection itemSection = itemsSection.getConfigurationSection(key);
                    if (itemSection != null) {
                        String modelName = itemSection.getString("model");
                        if (modelName != null) {
                            if (bedrockResourcePack != null)
                                plugin.getSLF4JLogger().warn("Custom item models are not supported in Bedrock resource packs yet: {}", modelName);
                            String namespace = FileUtils.getFirstResourceSubfolder(resourceFolder, config.file());
                            File modelFile = new File(resourceFolder, namespace + "/assets/models/" + modelName);
                            modelFile = FileUtils.detectFileExtension(modelFile, List.of(".json", ".lomodel"));
                            if (modelFile.exists() && modelFile.isFile()) {
                                if (modelFile.getName().endsWith(".json")) {
                                    createItemFile(resourcePack, "assets/lost_engine/items/" + key + ".json", "lost_engine:" + modelName.replace(".json", ""));
                                } else if (modelFile.getName().endsWith(".lomodel")) {
                                    plugin.getSLF4JLogger().error("LOModel format is not supported for item models yet: {}", modelFile.getAbsolutePath());
                                } else {
                                    plugin.getSLF4JLogger().error("Unknown model file for item model: {}", modelFile.getAbsolutePath());
                                }
                            } else {
                                plugin.getSLF4JLogger().error("Model file for item model not found: {}", modelFile.getAbsolutePath());
                            }
                        } else {
                            String textureName = itemSection.getString("texture");
                            if (textureName != null) {
                                String type = itemSection.getString("type", "generic").toLowerCase();
                                createItemModel(
                                        resourcePack,
                                        Key.key("lost_engine", "item/" + key),
                                        switch (type) {
                                            case "sword", "pickaxe", "axe", "shovel", "hoe" -> Key.key("item/handheld");
                                            default -> Key.key("item/generated");
                                        },
                                        Key.key("lost_engine", textureName)
                                );
                                createItemFile(resourcePack, "assets/lost_engine/items/" + key + ".json", "lost_engine:item/" + key);
                                if (bedrockResourcePack != null) {
                                    createBedrockTextureData(bedrockResourcePack, "textures/" + textureName, key);
                                }
                            }
                        }
                        ConfigurationSection nameSection = itemSection.getConfigurationSection("name");
                        if (nameSection != null) {
                            nameSection.getKeys(false).forEach(langCode -> {
                                String name = nameSection.getString(langCode);
                                if (name != null) {
                                    langFileGenerator.addTranslation(langCode, "item.lost_engine." + key, name);
                                }
                            });
                        }
                        ConfigurationSection elytraSection = itemSection.getConfigurationSection("elytra");
                        if (elytraSection != null) {
                            String texture = elytraSection.getString("texture", null);
                            resourcePack.jsonFile("assets/minecraft/equipment/%s.json".formatted(key.toLowerCase(Locale.ROOT)), JsonParser.parseString("""
                                    {
                                      "layers": {
                                        "wings": [
                                          {
                                            "texture": "lost_engine:%s",
                                            "use_player_texture": %b
                                          }
                                        ]
                                      }
                                    }
                                    """.formatted(texture, elytraSection.getBoolean("use_player_skin", false))));
                        }
                    }
                }
            }
            ConfigurationSection blocksSection = config.config().getConfigurationSection("blocks");
            if (blocksSection != null) {
                for (String key : blocksSection.getKeys(false)) {
                    ConfigurationSection blockSection = blocksSection.getConfigurationSection(key);
                    if (blockSection != null) {
                        String textureName = blockSection.getString("texture", null);
                        if (textureName != null) {
                            createBlockModel(
                                    resourcePack,
                                    Key.key("lost_engine", "block/" + key),
                                    Key.key("lost_engine", textureName)
                            );
                            createItemFile(resourcePack, "assets/lost_engine/items/" + key + ".json", "lost_engine:block/" + key);
                            Identifier resourceLocation = Identifier.parse("lost_engine:" + key);
                            if (BuiltInRegistries.BLOCK.containsKey(resourceLocation)) {
                                Block block = BuiltInRegistries.BLOCK.getValue(resourceLocation);
                                if (block instanceof CustomBlock customBlock) {
                                    blockStateGenerator.addBlockState(customBlock.getClientBlockState(), "lost_engine:block/" + key);
                                }
                            }
                        }
                        ConfigurationSection nameSection = blockSection.getConfigurationSection("name");
                        if (nameSection != null) {
                            nameSection.getKeys(false).forEach(langCode -> {
                                String name = nameSection.getString(langCode);
                                if (name != null) {
                                    langFileGenerator.addTranslation(langCode, "item.lost_engine." + key, name);
                                }
                            });
                        }
                    }
                }
            }
            ConfigurationSection materialsSection = config.config().getConfigurationSection("materials");
            if (materialsSection != null) {
                for (String key : materialsSection.getKeys(false)) {
                    ConfigurationSection materialSection = materialsSection.getConfigurationSection(key);
                    if (materialSection != null) {
                        String armorTexture = materialSection.getString("armor.texture", null);
                        if (armorTexture != null) {
                            resourcePack.jsonFile("assets/minecraft/equipment/%s.json".formatted(key.toLowerCase(Locale.ROOT)), JsonParser.parseString("""
                                    {
                                      "layers": {
                                        "humanoid": [
                                          {
                                            "texture": "lost_engine:%s"
                                          }
                                        ],
                                        "humanoid_leggings": [
                                          {
                                            "texture": "lost_engine:%s"
                                          }
                                        ]
                                      }
                                    }
                                    """.formatted(armorTexture, armorTexture)));
                        }
                    }
                }
            }
        });
        File[] files = resourceFolder.listFiles();
        if (files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    File texturesDir = new File(file, "assets/textures");
                    if (texturesDir.exists() && texturesDir.isDirectory()) {
                        addTexturesRecursively(resourcePack, bedrockResourcePack, texturesDir, "lost_engine");
                    }
                }
            }
        }
        langFileGenerator.build(resourcePack, bedrockResourcePack);
        blockStateGenerator.build(resourcePack);

        // TODO: Add options to disable oxipng and choose compression level
        File oxipngFolder = new File(plugin.getDataFolder(), "lostengine_files/oxipng");
        if (!oxipngFolder.isDirectory()) {
            oxipngFolder.mkdirs();
            plugin.getSLF4JLogger().info("Downloading oxipng for resource pack compression... " +
                    "(this will only happen once, if it fails you can download the file manually and place it in {} " +
                    "named {})", oxipngFolder.getAbsolutePath(), PngOptimizer.Os.current() == PngOptimizer.Os.WINDOWS ? "oxipng.exe" : "oxipng");
        }
        PngOptimizer.downloadOxipng(oxipngFolder.toPath()); // Downloads oxipng if not present
        resourcePack.build(resourcePackFile, dev.lost.furnace.resourcepackbuilder.ResourcePackBuilder.BuildOptions.MAX_COMPRESSION);
        if (bedrockResourcePack != null) {
            bedrockResourcePack.build(
                    FileUtils.withExtension(resourcePackFile, "mcpack"),
                    dev.lost.furnace.resourcepackbuilder.ResourcePackBuilder.BuildOptions.MAX_COMPRESSION
            );
        }
    }

    private static void addTexturesRecursively(ResourcePack resourcePack, @Nullable BedrockResourcePack bedrockResourcePack, @NotNull File texturesDirectory, String namespace) {
        Path baseDir = texturesDirectory.toPath();
        try (Stream<@NotNull Path> paths = Files.walk(baseDir)) {
            paths.filter(path -> Files.isRegularFile(path) && path.toString().endsWith(".png"))
                    .forEach(path -> {
                        String textureKey = baseDir.relativize(path).toString().replace("\\", "/");
                        try {
                            resourcePack.texture(Texture.file("assets/" + namespace + "/textures/" + textureKey, path.toFile()));
                            if (bedrockResourcePack != null)
                                bedrockResourcePack.texture(Texture.file("textures/" + textureKey, path.toFile()));
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                    });
        } catch (IOException e) {
            LostEngine.logger().error("Failed to add textures recursively", e);
        }
    }

    private static void createBlockModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key textureKey) {
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent("block/cube_all")
                        .texture("all", textureKey.asString())
        );
    }

    private static void createItemModel(@NotNull JavaResourcePack resourcePack, @NotNull Key modelKey, @NotNull Key parent, @NotNull Key textureKey) {
        resourcePack.model(
                Model.model("assets/" + modelKey.namespace() + "/models/" + modelKey.value() + ".json")
                        .parent(parent.asString())
                        .texture("layer0", textureKey.asString())
        );
    }

    private static void createItemFile(@NotNull ResourcePack resourcePack, String path, @NotNull String modelKey) {
        resourcePack.jsonFile(path, JsonParser.parseString("{\"oversized_in_gui\":true,\"model\":{\"type\":\"minecraft:model\",\"model\":\"%s\"}}".formatted(modelKey)));
    }

    private static void createBedrockTextureData(@NotNull BedrockResourcePack bedrockResourcePack, @Pattern("^textures/([a-zA-Z0-9_\\-/]+$)") String texturePath, @NotNull String itemName) {
        UnknownFile file = bedrockResourcePack.unknownFiles().get("textures/item_texture.json");
        String text = file != null ? file.file().getText() : "{\"texture_data\":{}}";
        JsonObject json = JsonParser.parseString(text).getAsJsonObject();
        JsonObject textureData = json.getAsJsonObject("texture_data");
        JsonObject item = new JsonObject();
        item.addProperty("textures", texturePath);
        textureData.add("lost_engine_" + itemName, item);
        bedrockResourcePack.unknownFile(UnknownFile.utf8("textures/item_texture.json", json.toString()));
    }

}
